# Generated by Django 4.0.3 on 2022-04-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UuidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='webapp.photo')),
            ],
            options={
                'verbose_name': 'Uuid Ссылка',
                'verbose_name_plural': 'Uuid Cсылки',
                'db_table': 'UuidLink',
            },
        ),
    ]
